// Curated roster overlay. Base stats + ability names/effects come from the
// GDD's dex_db.json; types, display glyphs, movepools (default 4 + trainable
// alternates) and recruit price tiers are canonical/curated here.
// price tiers (VP): common 1000, standard 2500, rare 5000, epic 8000, legend 12500
// (GDD range: 1,000–17,500 VP, 2,500 typical).

export const SPECIES = {
  Pikachu:      { types:['Electric'], glyph:'⚡', tier:'common', abilities:['Static','Lightning Rod'],
    moves:['Volt Tackle','Nuzzle','Quick Attack','Volt Switch'], alts:['Thunderbolt','Fake Out','Thunder','Play Rough'] },
  Charizard:    { types:['Fire','Flying'], glyph:'🔥', tier:'epic', mega:['Mega Charizard X','Mega Charizard Y'], abilities:['Blaze','Solar Power'],
    moves:['Flamethrower','Air Slash','Solar Beam','Roost'], alts:['Fire Blast','Hurricane','Dragon Claw','Sunny Day'] },
  Venusaur:     { types:['Grass','Poison'], glyph:'🌿', tier:'standard', mega:['Mega Venusaur'], abilities:['Overgrow','Chlorophyll'],
    moves:['Giga Drain','Sludge Bomb','Sleep Powder','Leech Seed'], alts:['Solar Beam','Leaf Storm','Protect','Sunny Day'] },
  Blastoise:    { types:['Water'], glyph:'🌊', tier:'standard', mega:['Mega Blastoise'], abilities:['Torrent','Rain Dish'],
    moves:['Surf','Ice Beam','Shell Smash','Protect'], alts:['Hydro Pump','Flash Cannon','Yawn','Rapid Spin'] },
  Alakazam:     { types:['Psychic'], glyph:'🥄', tier:'rare', mega:['Mega Alakazam'], abilities:['Magic Guard','Inner Focus'],
    moves:['Psychic','Focus Blast','Shadow Ball','Calm Mind'], alts:['Psyshock','Dazzling Gleam','Energy Ball','Protect'] },
  Gengar:       { types:['Ghost','Poison'], glyph:'👻', tier:'rare', mega:['Mega Gengar'], abilities:['Cursed Body'],
    moves:['Shadow Ball','Sludge Bomb','Focus Blast','Nasty Plot'], alts:['Hex','Hypnosis','Dazzling Gleam','Thunderbolt'] },
  Snorlax:      { types:['Normal'], glyph:'😴', tier:'standard', abilities:['Thick Fat'],
    moves:['Body Slam','Earthquake','Crunch','Rest'], alts:['Double-Edge','Yawn','Protect','Ice Punch'] },
  Dragonite:    { types:['Dragon','Flying'], glyph:'🐉', tier:'epic', mega:['Mega Dragonite'], abilities:['Multiscale','Inner Focus'],
    moves:['Dragon Dance','Dragon Claw','Extreme Speed','Roost'], alts:['Hurricane','Earthquake','Fire Punch','Ice Beam'] },
  Tyranitar:    { types:['Rock','Dark'], glyph:'🦖', tier:'epic', mega:['Mega Tyranitar'], abilities:['Sand Stream'],
    moves:['Rock Slide','Crunch','Dragon Dance','Earthquake'], alts:['Stone Edge','Stealth Rock','Fire Blast','Ice Beam'] },
  Metagross:    { types:['Steel','Psychic'], glyph:'🛡️', tier:'epic', mega:['Mega Metagross'], abilities:['Clear Body'],
    moves:['Meteor Mash','Zen Headbutt','Bullet Punch','Earthquake'], alts:['Iron Defense','Ice Punch','Rock Slide','Protect'] },
  Garchomp:     { types:['Dragon','Ground'], glyph:'🦈', tier:'epic', mega:['Mega Garchomp'], abilities:['Rough Skin'],
    moves:['Earthquake','Dragon Claw','Stone Edge','Swords Dance'], alts:['Draco Meteor','Fire Blast','Stealth Rock','Rock Slide'] },
  Lucario:      { types:['Fighting','Steel'], glyph:'🥋', tier:'rare', mega:['Mega Lucario'], abilities:['Inner Focus','Justified'],
    moves:['Close Combat','Meteor Mash','Extreme Speed','Swords Dance'], alts:['Aura Sphere','Flash Cannon','Nasty Plot','Bullet Punch'] },
  Gyarados:     { types:['Water','Flying'], glyph:'🌊', tier:'rare', mega:['Mega Gyarados'], abilities:['Intimidate','Moxie'],
    moves:['Waterfall','Dragon Dance','Crunch','Earthquake'], alts:['Hydro Pump','Hurricane','Protect','Stone Edge'] },
  Scizor:       { types:['Bug','Steel'], glyph:'✂️', tier:'rare', mega:['Mega Scizor'], abilities:['Technician'],
    moves:['Bullet Punch','U-turn','Swords Dance','Roost'], alts:['X-Scissor','Iron Head','Knock Off','Protect'] },
  Gardevoir:    { types:['Psychic','Fairy'], glyph:'💃', tier:'rare', mega:['Mega Gardevoir'], abilities:['Trace'],
    moves:['Moonblast','Psychic','Calm Mind','Thunderbolt'], alts:['Psyshock','Dazzling Gleam','Will-O-Wisp','Protect'] },
  Swampert:     { types:['Water','Ground'], glyph:'🐸', tier:'standard', mega:['Mega Swampert'], abilities:['Torrent'],
    moves:['Earthquake','Liquidation','Ice Punch','Stealth Rock'], alts:['Surf','Ice Beam','Rock Slide','Yawn'] },
  Blaziken:     { types:['Fire','Fighting'], glyph:'🐓', tier:'rare', mega:['Mega Blaziken'], abilities:['Speed Boost','Blaze'],
    moves:['Flare Blitz','Close Combat','Protect','Swords Dance'], alts:['Brave Bird','Stone Edge','Knock Off','Earthquake'] },
  Kangaskhan:   { types:['Normal'], glyph:'🦘', tier:'standard', mega:['Mega Kangaskhan'], abilities:['Scrappy'],
    moves:['Fake Out','Double-Edge','Sucker Punch','Earthquake'], alts:['Body Slam','Crunch','Ice Punch','Protect'] },
  Mawile:       { types:['Steel','Fairy'], glyph:'🪤', tier:'standard', mega:['Mega Mawile'], abilities:['Intimidate'],
    moves:['Play Rough','Iron Head','Sucker Punch','Swords Dance'], alts:['Knock Off','Stealth Rock','Protect','Crunch'] },
  Heracross:    { types:['Bug','Fighting'], glyph:'🪲', tier:'standard', mega:['Mega Heracross'], abilities:['Guts','Moxie'],
    moves:['Megahorn','Close Combat','Knock Off','Swords Dance'], alts:['Stone Edge','Bulk Up','Protect','Earthquake'] },
  Absol:        { types:['Dark'], glyph:'🌙', tier:'standard', mega:['Mega Absol'], abilities:['Pressure','Justified'],
    moves:['Knock Off','Sucker Punch','Play Rough','Swords Dance'], alts:['Will-O-Wisp','Taunt','Ice Beam','Protect'] },
  Aerodactyl:   { types:['Rock','Flying'], glyph:'🦅', tier:'rare', mega:['Mega Aerodactyl'], abilities:['Pressure'],
    moves:['Stone Edge','Earthquake','Dual Wingbeat','Taunt'], alts:['Stealth Rock','Roost','Crunch','Rock Slide'] },
  Houndoom:     { types:['Dark','Fire'], glyph:'🐺', tier:'standard', mega:['Mega Houndoom'], abilities:['Flash Fire'],
    moves:['Dark Pulse','Flamethrower','Nasty Plot','Sucker Punch'], alts:['Fire Blast','Sludge Bomb','Will-O-Wisp','Protect'] },
  Manectric:    { types:['Electric'], glyph:'🐕', tier:'common', mega:['Mega Manectric'], abilities:['Lightning Rod','Static'],
    moves:['Thunderbolt','Volt Switch','Flamethrower','Thunder Wave'], alts:['Thunder','Overheat','Protect','Rain Dance'] },
  Greninja:     { types:['Water','Dark'], glyph:'🥷', tier:'epic', mega:['Mega Greninja'], abilities:['Protean','Torrent'],
    moves:['Water Shuriken','Dark Pulse','Ice Beam','U-turn'], alts:['Hydro Pump','Gunk Shot','Toxic Spikes','Taunt'] },
  Excadrill:    { types:['Ground','Steel'], glyph:'⛏️', tier:'rare', mega:['Mega Excadrill'], abilities:['Sand Rush','Mold Breaker'],
    moves:['Earthquake','Iron Head','Rock Slide','Swords Dance'], alts:['Rapid Spin','Stealth Rock','X-Scissor','Protect'] },
  Dragapult:    { types:['Dragon','Ghost'], glyph:'🚀', tier:'epic', abilities:['Clear Body'],
    moves:['Dragon Darts','Shadow Ball','U-turn','Dragon Dance'], alts:['Draco Meteor','Hex','Will-O-Wisp','Thunderbolt'] },
  Gholdengo:    { types:['Steel','Ghost'], glyph:'🪙', tier:'epic', abilities:['Good as Gold'],
    moves:['Make It Rain','Shadow Ball','Nasty Plot','Recover'], alts:['Focus Blast','Thunderbolt','Steel Beam','Thunder Wave'] },
  Kingambit:    { types:['Dark','Steel'], glyph:'♟️', tier:'epic', abilities:['Supreme Overlord','Defiant'],
    moves:['Kowtow Cleave','Iron Head','Sucker Punch','Swords Dance'], alts:['Knock Off','Protect','Taunt','Brick Break'] },
  Corviknight:  { types:['Flying','Steel'], glyph:'🐦‍⬛', tier:'standard', abilities:['Pressure'],
    moves:['Brave Bird','Body Press','Iron Defense','Roost'], alts:['U-turn','Iron Head','Taunt','Tailwind'] },
  Incineroar:   { types:['Fire','Dark'], glyph:'🐯', tier:'rare', abilities:['Intimidate','Blaze'],
    moves:['Fake Out','Flare Blitz','Knock Off','Parting Shot'], alts:['Darkest Lariat','Will-O-Wisp','U-turn','Protect'] },
  Toxapex:      { types:['Poison','Water'], glyph:'🦑', tier:'standard', abilities:['Regenerator'],
    moves:['Scald','Toxic','Recover','Protect'], alts:['Poison Jab','Toxic Spikes','Liquidation','Icy Wind'] },
  Mimikyu:      { types:['Ghost','Fairy'], glyph:'🎭', tier:'rare', abilities:['Disguise'],
    moves:['Play Rough','Shadow Claw','Shadow Sneak','Swords Dance'], alts:['Wood Hammer','Taunt','Protect','Charm'] },
  Volcarona:    { types:['Bug','Fire'], glyph:'🦋', tier:'epic', abilities:['Flame Body'],
    moves:['Quiver Dance','Fiery Dance','Bug Buzz','Giga Drain'], alts:['Fire Blast','Hurricane','Protect','Will-O-Wisp'] },
  Azumarill:    { types:['Water','Fairy'], glyph:'🐰', tier:'common', abilities:['Huge Power','Thick Fat'],
    moves:['Play Rough','Aqua Jet','Liquidation','Belly Drum'], alts:['Knock Off','Ice Punch','Protect','Waterfall'] },
  Sylveon:      { types:['Fairy'], glyph:'🎀', tier:'standard', abilities:['Pixilate'],
    moves:['Hyper Voice','Psyshock','Calm Mind','Protect'], alts:['Moonblast','Shadow Ball','Yawn','Dazzling Gleam'] },
  Hydreigon:    { types:['Dark','Dragon'], glyph:'🐲', tier:'epic', abilities:['Levitate'],
    moves:['Dark Pulse','Draco Meteor','Flash Cannon','Nasty Plot'], alts:['Dragon Pulse','Fire Blast','U-turn','Taunt'] },
  Weavile:      { types:['Dark','Ice'], glyph:'❄️', tier:'rare', abilities:['Pressure'],
    moves:['Icicle Crash','Knock Off','Ice Shard','Swords Dance'], alts:['Taunt','Protect','Brick Break','Icy Wind'] },
  Pelipper:     { types:['Water','Flying'], glyph:'🕊️', tier:'common', abilities:['Drizzle'],
    moves:['Hurricane','Surf','U-turn','Roost'], alts:['Hydro Pump','Scald','Tailwind','Protect'] },
  Torkoal:      { types:['Fire'], glyph:'🐢', tier:'common', abilities:['Drought'],
    moves:['Flamethrower','Solar Beam','Stealth Rock','Yawn'], alts:['Body Press','Earth Power','Rapid Spin','Will-O-Wisp'] },
  'Alolan Ninetales': { types:['Ice','Fairy'], glyph:'🦊', tier:'rare', abilities:['Snow Warning'],
    moves:['Aurora Veil','Freeze-Dry','Moonblast','Blizzard'], alts:['Dazzling Gleam','Hypnosis','Protect','Icy Wind'] },
};

// Mega forms: stats read from dex_db entries of the same name.
// type/ability overrides are canonical; Champions-new megas (Dragonite,
// Greninja, Excadrill) keep base typing and take the ability listed in the dex.
export const MEGAS = {
  'Mega Charizard X': { base:'Charizard', types:['Fire','Dragon'],  ability:'Tough Claws' },
  'Mega Charizard Y': { base:'Charizard', types:['Fire','Flying'],  ability:'Drought' },
  'Mega Venusaur':    { base:'Venusaur',  types:['Grass','Poison'], ability:'Thick Fat' },
  'Mega Blastoise':   { base:'Blastoise', types:['Water'],          ability:'Mega Launcher' },
  'Mega Alakazam':    { base:'Alakazam',  types:['Psychic'],        ability:'Trace' },
  'Mega Gengar':      { base:'Gengar',    types:['Ghost','Poison'], ability:'Shadow Tag' },
  'Mega Dragonite':   { base:'Dragonite', types:['Dragon','Flying'], ability:null },
  'Mega Tyranitar':   { base:'Tyranitar', types:['Rock','Dark'],    ability:'Sand Stream' },
  'Mega Metagross':   { base:'Metagross', types:['Steel','Psychic'],ability:'Tough Claws' },
  'Mega Garchomp':    { base:'Garchomp',  types:['Dragon','Ground'],ability:'Sand Force' },
  'Mega Lucario':     { base:'Lucario',   types:['Fighting','Steel'],ability:'Adaptability' },
  'Mega Gyarados':    { base:'Gyarados',  types:['Water','Dark'],   ability:'Mold Breaker' },
  'Mega Scizor':      { base:'Scizor',    types:['Bug','Steel'],    ability:'Technician' },
  'Mega Gardevoir':   { base:'Gardevoir', types:['Psychic','Fairy'],ability:'Pixilate' },
  'Mega Swampert':    { base:'Swampert',  types:['Water','Ground'], ability:'Swift Swim' },
  'Mega Blaziken':    { base:'Blaziken',  types:['Fire','Fighting'],ability:'Speed Boost' },
  'Mega Kangaskhan':  { base:'Kangaskhan',types:['Normal'],         ability:'Parental Bond' },
  'Mega Mawile':      { base:'Mawile',    types:['Steel','Fairy'],  ability:'Huge Power' },
  'Mega Heracross':   { base:'Heracross', types:['Bug','Fighting'], ability:'Skill Link' },
  'Mega Absol':       { base:'Absol',     types:['Dark'],           ability:'Magic Bounce' },
  'Mega Aerodactyl':  { base:'Aerodactyl',types:['Rock','Flying'],  ability:'Tough Claws' },
  'Mega Houndoom':    { base:'Houndoom',  types:['Dark','Fire'],    ability:'Solar Power' },
  'Mega Manectric':   { base:'Manectric', types:['Electric'],       ability:'Intimidate' },
  'Mega Greninja':    { base:'Greninja',  types:['Water','Dark'],   ability:null },
  'Mega Excadrill':   { base:'Excadrill', types:['Ground','Steel'], ability:null },
};

// Held items implemented by the battle engine. VP prices come from dex_db
// facts where present, else the GDD defaults (held item 700, berry 400).
export const ITEMS = {
  'Leftovers':       { kind:'passive', desc:'Restores 1/16 max HP at the end of each turn.' },
  'Focus Sash':      { kind:'consumable', desc:'Survive a KO from full HP with 1 HP. Single use.' },
  'Choice Scarf':    { kind:'choice', boost:'spe', desc:'Speed x1.5, but locks into the first move used.' },
  'Choice Band':     { kind:'choice', boost:'atk', desc:'Attack x1.5, but locks into the first move used.' },
  'Choice Specs':    { kind:'choice', boost:'spa', desc:'Sp. Atk x1.5, but locks into the first move used.' },
  'Life Orb':        { kind:'passive', desc:'Moves deal 30% more damage; user loses 10% max HP per attack.' },
  'Assault Vest':    { kind:'passive', desc:'Sp. Def x1.5, but status moves cannot be selected.' },
  'Rocky Helmet':    { kind:'passive', desc:'Attackers making contact lose 1/6 of their max HP.' },
  'Sitrus Berry':    { kind:'consumable', desc:'Restores 25% max HP when HP falls below half. Single use.' },
  'Lum Berry':       { kind:'consumable', desc:'Cures any status condition or confusion. Single use.' },
  'Weakness Policy': { kind:'consumable', desc:'Attack and Sp. Atk +2 when hit super-effectively. Single use.' },
  'Expert Belt':     { kind:'passive', desc:'Super-effective moves deal 20% more damage.' },
  'Muscle Band':     { kind:'passive', desc:'Physical moves deal 10% more damage.' },
  'Wide Lens':       { kind:'passive', desc:'Accuracy x1.1.' },
  'Quick Claw':      { kind:'passive', desc:'20% chance to move first in its priority bracket.' },
  "King's Rock":     { kind:'passive', desc:'Damaging moves gain a 10% flinch chance.' },
  'White Herb':      { kind:'consumable', desc:'Restores lowered stats once. Single use.' },
  'Light Clay':      { kind:'passive', desc:'Reflect / Light Screen / Aurora Veil last 8 turns instead of 5.' },
  'Heat Rock':       { kind:'passive', desc:'Sun set by the holder lasts 8 turns.' },
  'Damp Rock':       { kind:'passive', desc:'Rain set by the holder lasts 8 turns.' },
  'Smooth Rock':     { kind:'passive', desc:'Sandstorm set by the holder lasts 8 turns.' },
  'Icy Rock':        { kind:'passive', desc:'Snow set by the holder lasts 8 turns.' },
  'Occa Berry':      { kind:'consumable', desc:'Halves damage from one super-effective Fire move. Single use.' },
  'Chople Berry':    { kind:'consumable', desc:'Halves damage from one super-effective Fighting move. Single use.' },
  'Yache Berry':     { kind:'consumable', desc:'Halves damage from one super-effective Ice move. Single use.' },
  'Shuca Berry':     { kind:'consumable', desc:'Halves damage from one super-effective Ground move. Single use.' },
  'Haban Berry':     { kind:'consumable', desc:'Halves damage from one super-effective Dragon move. Single use.' },
  'Colbur Berry':    { kind:'consumable', desc:'Halves damage from one super-effective Dark move. Single use.' },
};
